name: Build Solution and Run Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  checks: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET 9 (Preview)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests and store result
        id: test
        run: |
          dotnet test --configuration Release --no-build --logger "trx;LogFileName=results.trx" --results-directory TestResults || echo "TEST_FAILED=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Publish test report
        uses: zyborg/dotnet-tests-report@v1
        with:
          github-token: ${{ github.token }}}
          results-directory: TestResults
          report-name: Test Results
          report-title: Detailed Test Results

      - name: Fail workflow if tests failed
        if: env.TEST_FAILED == 'true'
        run: exit 1
