name: Publish Backend Docker Image

on:
  push:
    branches: [main]  

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Build da imagem Docker
        run: |
          docker build -t ghcr.io/${{ github.KaueSMoraes }}/backend:main -f ./Dockerfile .

      - name: Push da imagem para o GHCR
        run: |
          docker push ghcr.io/${{ github.KaueSMoraes }}/backend:main
