name: Executar Testes

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Rodar testes
        run: dotnet test --logger "trx;LogFileName=results.trx" --results-directory TestResults

      - name: Publicar relatório de testes
        uses: zyborg/dotnet-tests-report@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-directory: TestResults
          report-name: Test Results
          report-title: Test Results - Detalhado
